<?php
  // taken from resources/views/modals/ajax.phtml; it's unfortunately not on every page available, so linkenhancer has it's own
  // 
?>
<!-- A dynamic modal, with content loaded using AJAX. -->
<div class="modal fade" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true" id="le-ajax-modal" aria-labelledBy="le-ajax-modal-title">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div id="le-ajax-modal-title"></div>
        </div>
    </div>
</div>

<script>
  function eventLeAjaxModalLoad(event) {
    //console.debug('this', this, 'event', event);
    let that = this;
    let target = event.relatedTarget;
    if (event.type == 'click') { // for links on the visible modal that should load other content to be shown in this modal
      that = document.querySelector('#le-ajax-modal');
      target = event.target;
    }
    let modal_content = that.querySelector('.modal-content');

    // If we need to paste the result into a tom-select control
    modal_content.dataset.wtSelectId = target.dataset.wtSelectId;

    // Clear existing content (to prevent FOUC) and load new content.
    $(modal_content)
      .empty()
      .load(target.dataset.wtHref, function () {
        // Activate autocomplete fields
        this.querySelectorAll('.tom-select').forEach(element => webtrees.initializeTomSelect(element));
      });
  }

  document.addEventListener('DOMContentLoaded', function () {
    $('#le-ajax-modal')
      .on('show.bs.modal', eventLeAjaxModalLoad);
  });
</script>
