<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\I18N;
use Schwendinger\Webtrees\Helpers\MoreI18N;
use Schwendinger\Webtrees\Helpers\ClassName;

/**
 * @ var bool
 */

$hbaselevel = 4;

$wthbref_text = I18N::translate('Webtrees manual') . ' - ' . I18N::translate('Cross-reference');
$idprefix = 'wtchlp_';

$help_topics = [ // see: app/Http/RequestHandlers/HelpText.php
    'NAMES' => [
        'title' => MoreI18N::xlate('Names'),
        'text' => '',
        'level' => 1,
        'notoc' => true,
    ],
    
    'NAME' => [
        'title' => MoreI18N::xlate('Name'),
        'text' => view('help/name'),
        'level' => 2,
        'wthb' => 'Webtrees_Handbuch/Genealogischer_Prozess#Namen',
    ],

    'SURN' => [
        'title' => MoreI18N::xlate('Surname'),
        'text' => view('help/surname'),
        'level' => 2,
        'wthb' => 'Webtrees_Handbuch/Genealogischer_Prozess#Familiennamen',
    ],

    'ROMN' => [
        'title' => MoreI18N::xlate('Romanized'),
        'text' => view('help/romanized'),
        'level' => 2,
        'wthb' => '',
    ],

    '_HEB' => [
        'title' => MoreI18N::xlate('Hebrew'),
        'text' => view('help/hebrew'),
        'level' => 2,
        'wthb' => 'Webtrees_Handbuch/Genealogischer_Prozess#Namen_in_verschiedenen_Alphabeten',
    ],

    'DATE' => [
        'title' => MoreI18N::xlate('Date'),
        //'text' => not set - link to original help route; view needs parameter
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Anleitung_f%C3%BCr_Bearbeiter#Datumsangaben',
    ],

    'OBJE' => [
        'title' => MoreI18N::xlate('Media object'),
        'text' => view('help/media-object'),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Genealogischer_Prozess#Medien',
    ],

    'PLAC' => [
        'title' => MoreI18N::xlate('Place'),
        'text' => view('help/place'),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Genealogischer_Prozess#Orte',
    ],

    'data-fixes' => [
        'title' => MoreI18N::xlate('Data fixes'),
        'text' => view('help/data-fixes'),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Anleitung_f%C3%BCr_Verwalter#Datenkorrekturen',        
    ],

    'edit_SOUR_EVEN' => [
        'title' => MoreI18N::xlate('Associate events with this source'),
        'text' => view('help/source-events'),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Genealogischer_Prozess#Quellen_und_Archive',        
    ],

    'pending_changes' => [
        'title' => MoreI18N::xlate('Pending changes'),
        'text' => view('help/pending-changes', [
                        'is_admin' => Auth::isAdmin(),
                    ]),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Anleitung_f%C3%BCr_Moderatoren',
    ],

    'relationship-privacy' => [
        'title' => MoreI18N::xlate('Restrict to immediate family'),
        'text' => view('help/relationship-privacy'),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Anleitung_für_Administratoren/Benutzer#Benutzerverwaltung',
    ],

    'RESN' => [
        'title' => MoreI18N::xlate('Restriction'),
        'text' => view('help/restriction'),
        'level' => 1,
        'wthb' => 'Webtrees_Handbuch/Allgemeine_Erl%C3%A4uterung_des_Programms#Datenschutz',
    ],

];
?>
<p><?= I18N::translate('The context help topics provided by webtrees are listed below.') ?></p>
<ul>
<?php
// toc
foreach ($help_topics as $key => $attribs):
    $title   = $attribs['title'];
    if (!array_key_exists('notoc', $attribs)): ?>
    <li><a href="#<?= e($idprefix . $key) ?>"><?= $title?></a></li>
<?php
    endif;
endforeach;
?>
</ul>
<?php
// topics
foreach ($help_topics as $key => $attribs):
    $title   = $attribs['title'];
    $wthbref_href = $attribs['wthb'] ?? '';
    $hlevel  =  $hbaselevel + ($attribs['level'] ?? 1);?>
<h<?=$hlevel?> class="helpsection" id="<?= e($idprefix . $key) ?>"><?= $title ?></h<?= $hlevel ?>>
<?php if ($wthbref_href !==''):?>
<p><a class="wtreflink" href="<?= e($wthbref_href) ?>"><?= $wthbref_text ?></a></p>
<?php
    endif;
    if (array_key_exists('text', $attribs)) {
        if ($attribs['text'] !== '') {
            echo($attribs['text']);
        }
    } else {
        $route = route(ClassName::get(ClassName::HELP_TEXT), ['topic' => $key]);
        // important: links on a visible modal that should load other content into this modal 
        // must not set the attribute data-bs-toggle="modal", otherwise bootstrap toggles visibility of the modal
?>
<p><a class="modal-reload-link" href="#" data-bs-backdrop="static" data-bs-target="#wt-ajax-modal" data-wt-href="<?= e($route)?>"><?= I18N::translate('Further information can be found on a separate help page.') ?></a></p>
<?php
    }
endforeach;
?>
<script>
    document.querySelectorAll('.modal-reload-link').forEach(el => {
        el.addEventListener('click', (event) => {
            const link = event.target;
            const modal = link.closest('.modal');
            let modalContent = modal.querySelector('.modal-content');

            modalContent.replaceChildren(); //.innerHTML = ''; // empty()
            const url = link.dataset.wtHref;
            fetch(url)
                .then(response => response.text())
                // doesn't init scripts - see resources/js/webtrees/pages/ajax-modal.js
                .then(html => modalContent.innerHTML = html)
                .catch(err => console.error('LE-Mod AJAX reload error:', err));
        });
    });

    LinkEnhMod.initWtHelp('a.wtreflink');
</script>