<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var bool                  $link_active             enhanced links activated
 * @var bool                  $mdimg_active            markdown extended image support activated
 * @var array                 $mdsyntax                syntax format examples
 * @var string                $mdimg_css_class1
 * @var string                $mdimg_css_class2
 */
?>


<p><?= /*I18N: webtrees.pot */I18N::translate("Markdown is a simple system of formatting, used on websites such as Wikipedia. It uses unobtrusive punctuation characters to create headings and sub-headings, bold and italic text, lists, tables, etc.") ?></p>
<p><?= I18N::translate("Webtrees uses a CommonMark implementation and supports a subset of the markup") ?> 
 - <?= lcfirst(I18N::translate('See also')) ?> <a href="https://commonmark.thephpleague.com/">https://commonmark.thephpleague.com/</a>
</p>

<p><hr></p>
<h4>Markdown Syntax</h4>
<p><?= I18N::translate('The following overview only briefly lists common formatting options') ?>:</p>
<div style="overflow:scroll;">
<table class="table table-bordered table-sm">
    <thead>
        <tr>
            <th>
                Markdown
            </th>
            <th>
                <?= I18N::translate('Rendered output') ?>
            </th>
            <th>
                HTML
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($mdsyntax as $example) : ?>
        <tr>
            <td><pre><?= $example['md'] ?></pre></td>
            <td><?= isset($example['out']) ? $example['out'] : $example['html'] ?></td>
            <td><pre><?= e($example['html']) ?></pre></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
</div>

<p><b><?= I18N::translate('For more depth of detail') ?> <?= lcfirst(I18N::translate('See also')) ?>:</b>
    <ul>
        <li><a href="https://commonmark.org/help/">https://commonmark.org/help/</a></li>
        <li><a href="https://www.markdownguide.org/basic-syntax/">https://www.markdownguide.org/basic-syntax/</a></li>
    </ul>
</p>

<p><hr></p>
<h4><?= I18N::translate('Markdown editor for note textareas') ?></h4>
<p><?= /*I18N: MDE */ I18N::translate('The project “TinyMDE - A tiny, dependency-free embeddable HTML/JavaScript Markdown editor” is used') ?> 
  - <?= lcfirst(I18N::translate('See also')) ?>:
  <br />
    <a href="https://github.com/jefago/tiny-markdown-editor">https://github.com/jefago/tiny-markdown-editor</a>
    (<a href="https://github.com/jefago/tiny-markdown-editor/blob/main/LICENSE">MIT License</a>)
</p>

<?php if ($link_active) : ?>
<p><hr></p>
<h4><?= /*I18N: help md - section title */ I18N::translate('Enhanced Link Support') ?></h4>
<p><?= /*I18N: Enhanced Links */ I18N::translate('Different destinations can be addressed with a link, whereby the cross-reference is always the first link and the others are represented by attached clickable icons.') ?></p>
<p><?= /*I18N: Settings - prologue sentence 3 */ I18N::translate('By linking the notes to the GEDCOM data records (persons, families, sources, etc.) from the text, it is easier to replace the history module and thus also save this information in the GEDCOM file.') ?>
    <?= /*I18N: Settings - prologue sentence 5 */ I18N::translate('The link function is controlled via the anchor part of the URI.') ?>
</p>
<p><b>Syntax</b>:  <code>[<?= /*I18N: Enhanced Links code example 1 */ I18N::translate('Link display title') ?>](#@wt=i@I1@)</code></p>
<?php //TODO javascript routine for composing syntax help form config object
endif ?>

<?php if ($mdimg_active) : ?>
<p><hr></p>
<h4><?= /*I18N: help md - section title */I18N::translate('Markdown Image Support') ?></h4>
<p>
    <?= /*I18N: MD img - sentence 2 */ I18N::translate('The images are packed into a div container together with an image subtitle - which is also a link to the media data set for GEDCOM objects.') ?>
    <?= /*I18N: MD img - sentence 3 */ I18N::translate('The display can be customized as required using the following standard CSS classes or additional CSS classes.') ?>
</p>
<b>CSS</b>:<ul>
    <li><u><?= I18N::translate('Markdown image container standard css class') ?>:</u>
    <?= $mdimg_css_class1 ? '<code>' . $mdimg_css_class1 . '</code>' : I18N::translate('not defined') ?>
    </li>
    <li><u><?= I18N::translate('Markdown image title container standard css class') ?>:</u>
    <?= $mdimg_css_class2 ? '<code>' . $mdimg_css_class2 . '</code>' : I18N::translate('not defined') ?>
    </li>
</ul>


<b>Syntax</b>:<ul>
    <li><code>![<?= /*I18N: MD img code example 1 */ I18N::translate('alternate text for gedcom object') ?>](#@id=@M1@)</code>
    </li>
    <li><code>![<?= /*I18N: MD img code example 2 */ I18N::translate('alternate text for picture in public folder') ?>](#@public=webtrees.png "title")</code>
    </li>
    <li><code>![<?= /*I18N: MD img code example 3 */ I18N::translate('picture with defined height, width and additional css class') ?>](#@id=@M1@&h=200&w=200&cname=float-right)</code></li>
</ul>

<?php endif ?>

