<?php

declare(strict_types=1);

use Fisharebest\Webtrees\MediaFile;

/**
 * @var MediaFile $media_file
 * @var string $classnames
 * @var int $width
 * @var int $height
 * @var string|null $titleclassnames
 * @var bool $open_in_new_tab
 */

$classnames = trim($classnames);   
$divattrib = $classnames ? ' class="' . $classnames . '"' : '';
$titleclassnames = trim($titleclassnames);
$subattrib = $titleclassnames ? ' class="' . $titleclassnames . '"' : '';
if ($open_in_new_tab) {
    $subattrib .= ' target="blank"';
}

?>
<div<?= $divattrib ?>>
    <?= $media_file->displayImage($width, $height, 'contain', ['class' => 'img-thumbnail img-fluid']) ?>
    <a<?= $subattrib ?> href="<?= e($media_file->media()->url() ) ?>"><?= $media_file->media()->fullName() ?></a>
</div>