<?php

declare(strict_types=1);

use Fisharebest\Webtrees\MediaFile;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerModule;

/**
 * @var MediaFile $media_file
 * @var string $classnames
 * @var int $width
 * @var int $height
 */

 $classnames = trim($classnames);   
 $divattrib = $classnames ? ' class="' . $classnames . '"' : '';
?>
<div<?= $divattrib ?>>
    <?= $media_file->displayImage($width, $height, 'contain', ['class' => 'img-thumbnail img-fluid']) ?>
    <a class="<?= LinkEnhancerModule::STDCLASS_MD_IMG_TITLE ?>" href="<?= e($media_file->media()->url() ) ?>"><?= $media_file->media()->fullName() ?></a>
</div>