<?php

declare(strict_types=1);

/**
 * @var string $public_url
 * @var string $mime_type
 * @var string|null $classnames
 * @var string $alt_text
 * @var string|null $title
 * @var int|null $width
 * @var int|null $height
 * @var string|null $titleclassnames
 * 
 */

$classnames = trim($classnames);
$divattrib = $classnames ? ' class="' . $classnames . '"' : '';
$titleclassnames = trim($titleclassnames);
$subattrib = $titleclassnames ? ' class="' . $titleclassnames . '"' : '';
$title = $title ? ' title="' . e($title) . '"' : '';
//$title = $title ? '<span class="media-img-title">' . e($title) . '</span>' : '';
$width = isset($width) ? ' width="' . $width . '"' : '';
$height = isset($height) ? ' height="' . $height . '"' : '';

// <a type="image/?"> - necessary for display of data-title and gallery function of light box
?>
<div<?= $divattrib ?>>
  <a class="gallery cboxElement" type="<?= $mime_type ?>" href="<?= $public_url ?>" data-title="<?= e($alt_text); ?>">
    <img class="img-thumbnail img-fluid" dir="auto" src="<?= $public_url ?>" alt="<?= e($alt_text); ?>"<?= $title ?><?= $width ?><?= $height ?> />
    <span<?= $subattrib ?>><?= e($alt_text); ?></span>
  </a>
</div>