<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\DB;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerModule;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\View;

/**
 * @var string                  $title                  title of this custom module
 * @var string                  $description            description of this module
 * @var array<string>           $prefs                  list of chapter objects
 * @var string                  $jscode_linkpp          javascript code snippet from js-file, csv-export...
 * @var array<string>           $links                  links for: csvexport
 * @var array<int>              $tablerows              [total, assigned]
 * @var array                   $mdcfg                  [int total, int activated, array<string> trees_wo_md]
 */

$trees_w_md = join('</li><li>', $mdcfg['trees_w_md']);
$trees_w_md = $trees_w_md ?  "<ol><li>{$trees_w_md}</li></ol>" : '';

$trees_w_text = join('</li><li>', $mdcfg['trees_w_text']);
$trees_w_text = $trees_w_text ? "<ol><li>{$trees_w_text}</li></ol>" : '';
?>

<?= view('components/breadcrumbs', [
        'links' => [route(ControlPanel::class) => /*I18N: webtrees.pot */I18N::translate('Control panel'), $title]]) ?>

<h1><?= e($title) ?></h1>
<p><?= e($description) ?></p>

<p class="text-muted">
    <?= /*I18N: Settings - prologue sentence 1 */I18N::translate('The main purpose of this module is to make links to data records stored in family trees more convenient.') ?>
    <?= /*I18N: Settings - prologue sentence 2 */ I18N::translate('This avoids having to store fully qualified links, which impairs the portability of Gedcom data.') ?>
    <?= /*I18N: Settings - prologue sentence 3 */ I18N::translate('By linking the notes to the GEDCOM data records (persons, families, sources, etc.) from the text makes story telling much easier and thus also save this information in the GEDCOM file.'); ?>
    <?= /*I18N: Settings - prologue sentence 4 */ I18N::translate('The option of embedding the images already inserted in the family tree in the notes rounds off this approach.') ?>
    <br>
    <?= I18N::translate('See also') ?>: <a target="_blank" href="<?= LinkEnhancerModule::CUSTOM_WEBSITE ?>">GitHub README</a>
</p>

<div class="linkenhancer mb-5">
    <form method="post" enctype="multipart/form-data" onsubmit="return checkForm();">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">

        <p>&nbsp;</p>
        <h3><?= /*I18N: Settings - section title */I18N::translate('Activate Support') ?></h3>

        <div class="row">
            <!-- activate link++ --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">[1]
                        <?= I18N::translate('Activate enhanced links?') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [I18N::translate('no'), I18N::translate('yes')],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                            <p><?= /*I18N: Enhanced Links */ I18N::translate('This function is implemented via Javascript and only affects links in notes and HTML blocks on the client side.') ?>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- md active --><?php $prefId = LinkEnhancerModule::PREF_MD_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        [2] <?= I18N::translate('Markdown enhancements') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [I18N::translate('no'), I18N::translate('yes')],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                            <p><?= /*I18N: MD img - sentence 1 */ I18N::translate('Only works in notes that are formatted with Markdown.') ?>
                            </p>
                            <p style="color: gray;"><strong><?= /*I18N: MDE */ I18N::translate("Precondition: Tree preference '%s' need to be set to markdown.", /*I18N: webtrees.pot */ I18N::translate('Format text and notes')) ?></strong>
                            <table style="color: gray;">
                              <thead><tr>
                                <th style="background-color: lightgreen; min-width:150px; text-align: center;">markdown</th>
                                <th style="background-color: rgba(236, 74, 34, 0.52); min-width:150px; text-align: center;">text</th>
                              </tr></thead>
                              <tbody><tr>
                                <td><?= $trees_w_md ?></td>
                                <td><?= $trees_w_text ?></td>
                            </tr></tbody>
                            </table>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>
           
            <!-- show wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        [3] <?= I18N::translate('Show Help Link') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                I18N::translate('no'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                            <p>
                                <?= /*I18N: */ I18N::translate("A context-sensitive link to the German webtrees manual can be added by javascript to the small navigation menu.") ?>
                                <?= /*I18N: */ I18N::translate("If this feature is also desired in the admin backend, patch P002 would need to be applied or at least the custom module vesta_common would need to be installed."); ?>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- home link --><?php $prefId = LinkEnhancerModule::PREF_HOME_LINK_TYPE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        [4] <?= I18N::translate('Site title as home link') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: home link */ I18N::translate('home page of the current tree'),
                                /*I18N: home link */ I18N::translate('my page of the registered user')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>
        </div>

        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= /*I18N: webtrees.pot */ I18N::translate('save') ?>
        </button>

        <hr/>
        <h3><?= /*I18N: Settings - section title */ I18N::translate('More options') ?></h3>

        <div class="row">
            <!-- debug info in js console --><?php $prefId = LinkEnhancerModule::PREF_JS_DEBUG_CONSOLE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Output of debug information on the JS console') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>

        <h4 style="border-bottom:1px solid lightgray; margin-top: 1.2em;">[1] <?= /*I18N: Settings - section title */I18N::translate('Enhanced Link Support') ?></h4>
        <div class="row">
            <!-- links++ javascript --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_JS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('JavaScript for additional link targets') . ' (' . /*I18N: webtrees.pot */I18N::translate('optional') . ')' ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <textarea id="<?= $prefId ?>" name="<?= $prefId ?>" class="form-control font-monospace" dir="ltr" rows="5"><?= e($prefs[$prefId]) ?></textarea>
                <div class="form-text">
                    <p><?= /*I18N: Enhanced Links js */ I18N::translate('The JavaScript object overwrites and supplements the predefined settings, which are taken from the following code excerpt and can also serve as a reference point for adjustments.') ?></p>
                    <textarea class="form-control font-monospace" dir="ltr" rows="5" disabled readonly wrap="off" style="font-size:0.9em; color: gray;"><?= e($jscode_linkpp) ?></textarea>
                    <p><?= /*I18N: Enhanced Links js */ I18N::translate('Any CSS rules required are best added via the “CSS and JS” module.') ?>
                       <?= /*I18N: Enhanced Links js */ I18N::translate('Only the definition of the icon as a background image is actually needed - referencing as data: URL.') ?> <?= I18N::translate('See also') ?>: <a href="https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/data">mdn web docs - data: URLs</a>
                       <br />
                       <code>.icon-whatever { background-image: url(...) }</code>
                    </p>
                </div>
            </div>

        </div>


        <h4 style="border-bottom:1px solid lightgray; margin-top: 1.2em;">[2] <?= /*I18N: Settings - section title */I18N::translate('Markdown enhancements') ?></h4>
        <div class="row">
            <!-- md img active --><?php $prefId = LinkEnhancerModule::PREF_MD_IMG_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <strong><?= I18N::translate('Activate markdown image tweak?') ?></strong>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [I18N::translate('no'), I18N::translate('yes')],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>

        <!-- md img stdclass --><?php $prefId = LinkEnhancerModule::PREF_MD_IMG_STDCLASS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('Markdown image container standard css class') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text" value="<?= e($prefs[$prefId]) ?>">
            </div>

            <!-- md img title stdclass --><?php $prefId = LinkEnhancerModule::PREF_MD_IMG_TITLE_STDCLASS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('Markdown image title container standard css class') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                       value="<?= e($prefs[$prefId]) ?>">
            </div>

            <!-- mde active --><?php $prefId = LinkEnhancerModule::PREF_MDE_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <strong><?= I18N::translate('Markdown editor for note textareas') ?></strong>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [I18N::translate('no'), I18N::translate('yes')],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- md extensions active --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <strong><?= I18N::translate('Markdown extensions') ?></strong>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [I18N::translate('no'), I18N::translate('yes')],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>        

        <h4 style="border-bottom:1px solid lightgray; margin-top: 1.2em;">[3] <?= /*I18N: Settings - section title */ I18N::translate('Webtrees manual') ?></h4>
        <div class="row">
            <!-- prepend faicon to wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_FAICON; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <i class="fa-solid fa-circle-question"></i> <?= I18N::translate('Precede the help link with an icon') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                I18N::translate('no'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>
        
            <!-- support subcontext wthb-links --><?php $prefId = LinkEnhancerModule::PREF_WTHB_SUBCONTEXT; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Help link for subcontext topics') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                I18N::translate('no'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>

            <!-- full-text search and toc --><?php $prefId = LinkEnhancerModule::PREF_WTHB_TOCNSEARCH; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate("Full-text search") . ' / ' . I18N::translate('Table of contents') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                I18N::translate('no'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>

            <!-- wthb mapping data table -->
            <div class="col-sm-3 col-form-label wt-page-options-label">
                <?= I18N::translate('Data table') ?>
            </div>
            <div class="col-sm-9 wt-page-options-value">
                <div class="form-text">
                    <p><?= /*I18N: WTHB Link table */ I18N::translate('The context is established by assigning the routes used in webtrees to the corresponding sections in the manual.') ?>
                        <br>
                        <?= /*I18N: WTHB Link table */ I18N::translate('The data is stored in the database table') ?>:
                        <code><?= DB::prefix(LinkEnhancerModule::HELP_TABLE) ?></code>
                        <em>(<strong><?= /*I18N: WTHB Link table rows */ I18N::translate('Data rows') ?>:</strong>
                            <?= /*I18N: WTHB Link table rows assigned/total */ I18N::translate('%s of %s assigned', $tablerows['assigned'] ?? 0, $tablerows['total'] ?? 0) ?>)</em>
                    </p>
                </div>                    
                <div class="row mt-1">
                    <div class="col-5 d-flex align-items-center justify-content-start">
                        <a class="btn btn-secondary"
                            href="<?= e($links['routeimport']) ?>"><?= I18N::translate('Import registered routes') ?></a>
                    </div>
                    <div class="col-2 d-flex align-items-center justify-content-start" title="<?= e(I18N::translate('truncate table before import routes or csv file')) ?>">
                        <input type="checkbox" class="form-check-input me-1" name="table-truncate" id="table-truncate" value="1">
                        <label class="form-check-label ms-1 mb-0" for="table-truncate"> <?= I18N::translate('Table truncate') ?></label>
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-end">
                        <a class="btn btn-secondary"
                            href="<?= e($links['resetroutes']) ?>"><?= I18N::translate('Reset routes to delivery status') ?></a>
                    </div>

                </div>
                <div class="row mt-3 mb-1">
                    <div class="col-5 d-flex align-items-center justify-content-start">
                        <button type="submit" class="btn btn-secondary" formaction="<?= e($links['csvimport']) ?>">
                            <?= I18N::translate('CSV-Import') ?>
                        </button>
                    </div>
                    <div class="col-2 d-flex align-items-center justify-content-center">
                        <label for="csv-separator" class="me-1 mb-0"> <?= I18N::translate('Separator') ?></label>
                        <input class="form-control form-control-sm text-center" type="text" id="csv-separator" name="csv-separator" size="3" maxlength="3" value=";" required>
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-end">
                        <button type="submit" class="btn btn-secondary" formaction="<?= e($links['csvexport']) ?>">
                            <?= I18N::translate('CSV-Export') ?>
                        </button>

                    </div>
                </div>
                <div class="row mt-1 mb-1">
                    <label for="csv-file" class="col-sm-3 mt-2">
                        <?= I18N::translate('CSV import file') ?>
                    </label>
                
                    <div class="col-sm-9">
                        <input id="csv-file" type="file" name="csv-file" class="form-control">
                    </div>
                </div>
                <div class="row mt-1 mb-3">
                    <label for="encoding" class="col-sm-3 mt-2">
                        <?= /*I18N: webtrees.pot */ I18N::translate('Character encoding') ?>
                    </label>
                    
                    <div class="col-sm-9">
                        <?= view('components/select', ['name' => 'encoding', 'selected' => '', 'options' => ['' => /*I18N: webtrees.pot */I18N::translate('automatic')] + Registry::encodingFactory()->list()]) ?>
                    </div>
                </div>
            </div>
        
            <!-- auto update to wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_UPDATE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Automatically refresh data table when module is updated') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                I18N::translate('no'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>
            
            <!-- genwiki std link --><?php $prefId = LinkEnhancerModule::PREF_GENWIKI_LINK; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('Link to GenWiki') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                    value="<?= e($prefs[$prefId]) ?>">
                <div class="form-text">
                    <p><?= /*I18N: WTHB Link */ I18N::translate('This is the base link that is combined with the relative context links from the database table.') ?>
                    </p>
                </div>
            </div>
        
            <!-- wthb std link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_STD_LINK; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('Standard Link to webtrees manual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                    value="<?= e($prefs[$prefId]) ?>">
                <div class="form-text">
                    <p><?= /*I18N: WTHB Link */ I18N::translate('This fallback link is used, when no specific context link was defined.') ?>
                    </p>
                </div>
            </div>

            <!-- translate wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_TRANSLATE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= /*I18N: wthb link setting option */ I18N::translate('Open webtrees manual URL with Google Translate?') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: wthb translate */ I18N::translate('user defined'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>
        </div>


        <h4 style="border-bottom:1px solid lightgray; margin-top: 1.2em;">[4] <?= /*I18N: Settings - section title */ I18N::translate('Home link') ?></h4>
        <div class="row">
            <!-- home link --><?php $prefId = LinkEnhancerModule::PREF_HOME_LINK_JSON; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('JSON for home link styling') . ' (' . /*I18N: webtrees.pot */ I18N::translate('optional') . ')' ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <textarea id="<?= $prefId ?>" name="<?= $prefId ?>" class="form-control font-monospace" dir="ltr"
                    rows="5"><?= e($prefs[$prefId]) ?></textarea>
                <div class="form-text">
                    <p><?= /*I18N: Home link js */ I18N::translate('JSON object that can be used to dynamically apply CSS styles for the home link that match the current theme.') ?>
                    <br>
                    <?= /*I18N: Home link js */ I18N::translate('Standard CSS class name') ?>: <code><?= LinkEnhancerModule::STDCLASS_HOME_LINK ?></code>
                    </p>
                    <p><?= /*I18N: Home link js */ I18N::translate('Example') ?>: <code><?= LinkEnhancerModule::EXAMPLE_HOME_LINK_JSON ?></code></p>
                </div>
            </div>
        </div>
        <p>&nbsp;</p>

        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= /*I18N: webtrees.pot */I18N::translate('save') ?>
        </button>
    </form>
</div>

<?php View::push('javascript') ?>
<script>
    function checkForm(message) {
        const showError = (elem, msg) => {
            let errId = 'error-' + elem.attr('id');
            let errElem = $(`#${errId}`);
            console.log(errElem);
            if (errElem.length == 1) {
                $(errElem).text(msg);
            } else {
                $(elem).after(`<div id="${errId}" class="error">${msg}</div>`);
            }
        }
        
        let firstErrElem = null;

        let linkspp = $('#<?= LinkEnhancerModule::PREF_LINKSPP_JS; ?>');
        let jsString = linkspp.val().trim();
        if (jsString) {
            try {
                eval(`() => { let a = ${jsString}}`);
            } catch (e) { 
                showError(linkspp, '<?= e(I18N::translate('Javascript is invalid')) ?>: ' + e.message);
                firstErrElem ??= linkspp;
            }
        }

        let homelink = $('#<?= LinkEnhancerModule::PREF_HOME_LINK_JSON; ?>');
        let jsonString = homelink.val().trim();
        if (jsonString) {
            try {
                const obj = JSON.parse(jsonString); // Syntax-Validierung
            } catch (e) {
                showError(homelink, '<?= e(I18N::translate('JSON is invalid')) ?>');
                firstErrElem ??= homelink;
            }
        }

        if (firstErrElem) {
            $(firstErrElem).get(0).scrollIntoView({behavior: 'smooth'});
            return false;
        }
        return true;
    }
</script>
<?php View::endpush() ?>

<?php View::push('styles') ?>
<style>
.error {
    color: #d00;
    font-weight: bold;
}
</style>
<?php View::endpush() ?>