<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\I18N;
use Schwendinger\Webtrees\Helpers\ClassName;
use Schwendinger\Webtrees\Helpers\MoreI18N;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerModule;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerUtils as Utils;

/**
 * @var array<string>           $prefs                  list of chapter objects
 * @var array<string>           $links                  links
 * @var string                  $jscode_linkpp          javascript code snippet from js-file, csv-export...
 */

$title_reset_all = e(I18N::translate('Reset list item access level overwrites - %s', MoreI18N::xlate('All')));
$title_reset_access_level = e(I18N::translate('Reset list item access level overwrites - %s', I18N::translate('with configured access level')));

$link_params = is_array($links['resetlist_params'] ?? null) ? (array) $links['resetlist_params'] : null;
$link_reset_all = null;
$link_reset_access_level = null;
if (is_array($link_params)) {
    $link_reset_all = route('module', $link_params);
    $access_level = null;
    try {
        $access_level = (int) $prefs[LinkEnhancerModule::PREF_LINKSPP_OVERVIEW_ACCESS];
    } catch (Throwable $e) {}

    if (is_int($access_level)) {
        $link_params['access_level'] = $access_level;
        $link_reset_access_level = route('module', $link_params);
    }
}
?>
        <div class="row">
<section class="openinnewtab">
            <!-- links++ open in new tab --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_OPEN_IN_NEW_TAB; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= /*I18N: see also fancy-research-links */ I18N::translate('Open links in a new tab') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= Utils::insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>
            </fieldset>
</section>

            <!-- links++ javascript --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_JS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('JavaScript for additional link targets') . ' (' . MoreI18N::xlate('optional') . ')' ?>
            </label>
            <div class="col-sm-9 wt-page-options-value mt-2">
                <textarea id="<?= $prefId ?>" name="<?= $prefId ?>" class="form-control font-monospace" dir="ltr" rows="5"><?= e($prefs[$prefId]) ?></textarea>
                <div class="form-text">
                    <p><?= /*I18N: Enhanced Links js */ I18N::translate('The JavaScript object overwrites and supplements the predefined settings, which are taken from the following code excerpt and can also serve as a reference point for adjustments.') ?></p>
                    <textarea class="form-control font-monospace" dir="ltr" rows="5" disabled readonly wrap="off" style="font-size:0.9em; color: gray;"><?= e($jscode_linkpp) ?></textarea>
                    <p><?= /*I18N: Enhanced Links js */ I18N::translate('Any CSS rules required are best added via the “CSS and JS” module.') ?>
                       <?= /*I18N: Enhanced Links js */ I18N::translate('Only the definition of the icon as a background image is actually needed - referencing as data: URL.') ?> <?= I18N::translate('See also') ?>: <a href="https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/data">mdn web docs - data: URLs</a>
                       <br />
                       <code>.icon-whatever { background-image: url(...) }</code>
                    </p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3 col-form-label wt-page-options-label">
                <?= I18N::translate('Non-admin cross-reference overview') ?>
            </div>        
        </div>

        <div class="row">
            <!-- links++ overview max rows --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_OVERVIEW_MAX_ROWS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label sub" for="<?= $prefId ?>">
                <?= I18N::translate('Max rows') ?>
            </label>
            <div class="col-sm-3 wt-page-options-value mt-2">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                    value="<?= e($prefs[$prefId]) ?>">
            </div>
            <div class="col-sm-6 mt-2 form-text">
            </div>

            <!-- links++ overview access level --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_OVERVIEW_ACCESS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label sub" for="<?= $prefId ?>">
                <?= MoreI18N::xlate('Access level') ?>
            </label>
            <div class="col-sm-3 wt-page-options-value mt-2">
                <?= view('components/select', [
                    'id' => $prefId,
                    'name' => $prefId,
                    'selected' => $prefs[$prefId],
                    'options' => Auth::accessLevelNames()
                ]) ?>
            </div>
            <?php
                $access_level = null;
                try {
                    $access_level = (int) $prefs[$prefId];
                } catch (Throwable $e) {}
                $count = LinkEnhancerModule::countListAccessOverwrites($access_level);
            ?>
            <div class="col-sm-6 mt-2 form-text">
                <?= I18N::translate('Per-tree overrides are available  in the control panel') ?> - 
                <span style="text-align: center; line-height: inherit;"><?= view('icons/list') ?></span>
                <a href="<?= e(route(ClassName::get(ClassName::MODULES_LISTS))) ?>">
                    <?= I18N::translate('Lists') ?>
                </a>
                <ul>
                    <li>
                        <?= MoreI18N::xlate('Total') . ': ' . ($count['total'] ?? 0) ?>
                        <?php if ($link_reset_all): ?>
                        <a class="confirm-action"
                            href="<?= e($link_reset_all) ?>"
                            data-confirm-message="<?= $title_reset_all ?>"
                            title="<?= $title_reset_all ?>">
                            <?= MoreI18N::xlate('reset') ?>
                        </a>
                        <?php endif; ?>
                    </li>
                    <li>
                        <?= I18N::translate('of which with this access level') . ': ' . ($count['access_level'] ?? 0) ?>
                        <?php if ($link_reset_access_level): ?>
                        <a class="confirm-action" 
                            href="<?= e($link_reset_access_level) ?>" 
                            data-confirm-message="<?= $title_reset_access_level ?>" 
                            title="<?= $title_reset_access_level ?>">
                            <?= MoreI18N::xlate('reset') ?>
                        </a>
                        <?php endif; ?>
                    </li>
                </ul>
            </div>
        </div>
<style>
    .confirm-action {
        color: red;
        margin-left: 2.0em;
        font-style: italic;
    }
</style>
<script>
    document.querySelectorAll('.confirm-action').forEach(link => {
        link.addEventListener('click', event => {
            const message = event.currentTarget.dataset.confirmMessage;
            if (!confirm("<?= I18N::translate('Confirmation Prompt - Do you really want to perform this action?') ?>" + "\n" + message)) {
                event.preventDefault();
                return;
            }
        });
    });
</script>        