<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerModule;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerUtils As Utils;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Registry;

/**
 * @var string                  $title                  title of this custom module
 * @var string                  $description            description of this module
 * @var array<string>           $prefs                  list of chapter objects
 * @var string                  $jscode_linkpp          javascript code snippet from js-file, csv-export...
 * @var array<string>           $links                  links for: csvexport
 * @var array<int>              $tablerows              [total, assigned]
 * @var array                   $mdcfg                  [int total, int activated, array<string> trees_wo_md]
 * @var bool                    $vesta_common_enabled
 * @var string                  $mde_custom             registrations of custom modules
 */

function getFormButtons(string $idSuffix):string { 
    ob_start();?>
        <div class="row">
            <div class="col-6 d-flex align-items-center justify-content-start">
                <button type="submit" class="btn btn-primary">
                    <?= view('icons/save') ?>
                    <?= /*I18N: webtrees.pot */ I18N::translate('save') ?>
                </button>
            </div>

            <div class="col-6 d-flex align-items-center justify-content-end">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle settings-dropdown" id="settings-dropdown<?= $idSuffix ?>" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <?= I18N::translate('Settings') ?>...
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="settings-dropdown<?= $idSuffix ?>">
                        <li><a class="dropdown-item settings-reset" href="#"><?= /*I18N: webtrees.pot */ I18N::translate('reset') ?></a></li>
                        <li><a class="dropdown-item settings-reset-to-default" href="#"><?= I18N::translate('reset to default') ?></a></li>
                        <li><a class="dropdown-item settings-json-export" href="#"><?= I18N::translate('JSON export') ?></a></li>
                        <li><a class="dropdown-item settings-json-import" href="#"><?= I18N::translate('JSON import') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
<?php
    return ob_get_clean();
}

$module = Registry::container()->get(LinkEnhancerModule::class);
?>

<?= view('components/breadcrumbs', [
        'links' => [route(ControlPanel::class) => /*I18N: webtrees.pot */I18N::translate('Control panel'), $title]]) ?>

<h1 id="top"><?= e($title) ?></h1>
<p><?= e($description) ?></p>

<p class="text-muted">
    <?= /*I18N: Settings - prologue sentence 1 */I18N::translate('The main purpose of this module is to make links to data records stored in family trees more convenient.') ?>
    <?= /*I18N: Settings - prologue sentence 2 */ I18N::translate('This avoids having to store fully qualified links, which impairs the portability of Gedcom data.') ?>
    <?= /*I18N: Settings - prologue sentence 3 */ I18N::translate('By linking the notes to the GEDCOM data records (persons, families, sources, etc.) from the text makes story telling much easier and thus also save this information in the GEDCOM file.'); ?>
    <?= /*I18N: Settings - prologue sentence 4 */ I18N::translate('The option of embedding the images already inserted in the family tree in the notes rounds off this approach.') ?>
    <br>
    <?= I18N::translate('See also') ?>: <a target="_blank" href="<?= LinkEnhancerModule::CUSTOM_WEBSITE ?>">GitHub README</a>
</p>

<div class="linkenhancer mb-5">
    <form method="post" enctype="multipart/form-data" onsubmit="return checkForm();">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">

        <p>&nbsp;</p>
        <h3><?= /*I18N: Settings - section title */I18N::translate('Activate Support') ?></h3>

<?= view($module->name() . '::' . 'settings-main', [
    'prefs' => $prefs,
    'mdcfg' => $mdcfg
]) ?>

<?= getFormButtons('1') ?>

        <hr class="div" />
        <h3><?= /*I18N: Settings - section title */ I18N::translate('More options') ?></h3>

        <div class="row">
            <!-- debug info in js console --><?php $prefId = LinkEnhancerModule::PREF_JS_DEBUG_CONSOLE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Output of debug information on the JS console') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= Utils::insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- open links in new tab - global --><?php $prefId = LinkEnhancerModule::PREF_OPEN_IN_NEW_TAB; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= /*I18N: see also fancy-research-links */ I18N::translate('Open links in a new tab') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: */ I18N::translate('user defined'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>            
        </div>

        <h4 class="subdiv">[1] <a name="section1" href="#top"><?= /*I18N: Settings - section title */I18N::translate('Enhanced Link Support') ?></a></h4>
<section id="options1">
<?= view($module->name() . '::' . 'settings-le', [
    'prefs' => $prefs,
    'jscode_linkpp' => $jscode_linkpp,
]) ?>
</section>

        <h4 class="subdiv">[2] <a name="section2" href="#top"><?= /*I18N: Settings - section title */I18N::translate('Markdown enhancements') ?></a></h4>
<section id="options2">
<?= view($module->name() . '::' . 'settings-md', [
    'prefs'      => $prefs,
    'mde_custom' => $mde_custom,
]) ?>
</section>

        <h4 class="subdiv">[3] <a name="section3" href="#top"><?= /*I18N: Settings - section title */ I18N::translate('Webtrees manual') ?></a></h4>
<section id="options3">
<?= view($module->name() . '::' . 'settings-wthb', [
    'prefs' => $prefs,
    'links' => $links,
    'tablerows' => $tablerows,
    'vesta_common_enabled' => $vesta_common_enabled
]) ?>
</section>

        <h4 class="subdiv">[4] <a name="section4" href="#top"><?= /*I18N: Settings - section title */ I18N::translate('Home link') ?></a></h4>
<section id="options4">
<?= view($module->name() . '::' . 'settings-home', [
    'prefs' => $prefs
]) ?>
</section>

        <p>&nbsp;</p>

<?= getFormButtons('2') ?>
    </form>
</div>

<?= view($module->name() . '::' . 'settings-jscss', []) ?>