<?php

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\DB;
use Schwendinger\Webtrees\Module\LinkEnhancer\LinkEnhancerModule;
use Schwendinger\Webtrees\Module\LinkEnhancer\Factories\CustomMarkdownFactory;
use Schwendinger\Webtrees\Module\LinkEnhancer\Factories\ExtensionSettingOption;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Webtrees;

/**
 * @var string                  $title                  title of this custom module
 * @var string                  $description            description of this module
 * @var array<string>           $prefs                  list of chapter objects
 * @var string                  $jscode_linkpp          javascript code snippet from js-file, csv-export...
 * @var array<string>           $links                  links for: csvexport
 * @var array<int>              $tablerows              [total, assigned]
 * @var array                   $mdcfg                  [int total, int activated, array<string> trees_wo_md]
 * @var bool                    $vesta_common_enabled
 */

function prefixKeysToValues(array $data, string $separator = ': '): array
{
    foreach ($data as $key => &$value) {
        $value = $key . $separator . $value;
    }
    unset($value);
    return $data;
}

function insertNoYesInlineRadiobuttons(string $id, string $value): string {
    return view('components/radios-inline', [
        'id' => $id,
        'name' => $id,
        'options' => [
            /*I18N: webtrees.pot */ I18N::translate('no'),
            /*I18N: webtrees.pot */ I18N::translate('yes')
        ],
        'selected' => (int) $value
    ]);
}

$trees_w_md = join('</li><li>', $mdcfg['trees_w_md']);
$trees_w_md_cnt = count($mdcfg['trees_w_md']);
$trees_w_md = $trees_w_md ?  "<ol class=\"treelist\"><li>{$trees_w_md}</li></ol>" : '';

$trees_w_text = join('</li><li>', $mdcfg['trees_w_text']);
$trees_w_text_cnt = count($mdcfg['trees_w_text']);
$trees_w_text = $trees_w_text ? "<ol class=\"treelist\"><li>{$trees_w_text}</li></ol>" : '';
?>

<?= view('components/breadcrumbs', [
        'links' => [route(ControlPanel::class) => /*I18N: webtrees.pot */I18N::translate('Control panel'), $title]]) ?>

<h1 id="top"><?= e($title) ?></h1>
<p><?= e($description) ?></p>

<p class="text-muted">
    <?= /*I18N: Settings - prologue sentence 1 */I18N::translate('The main purpose of this module is to make links to data records stored in family trees more convenient.') ?>
    <?= /*I18N: Settings - prologue sentence 2 */ I18N::translate('This avoids having to store fully qualified links, which impairs the portability of Gedcom data.') ?>
    <?= /*I18N: Settings - prologue sentence 3 */ I18N::translate('By linking the notes to the GEDCOM data records (persons, families, sources, etc.) from the text makes story telling much easier and thus also save this information in the GEDCOM file.'); ?>
    <?= /*I18N: Settings - prologue sentence 4 */ I18N::translate('The option of embedding the images already inserted in the family tree in the notes rounds off this approach.') ?>
    <br>
    <?= I18N::translate('See also') ?>: <a target="_blank" href="<?= LinkEnhancerModule::CUSTOM_WEBSITE ?>">GitHub README</a>
</p>

<div class="linkenhancer mb-5">
    <form method="post" enctype="multipart/form-data" onsubmit="return checkForm();">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">

        <p>&nbsp;</p>
        <h3><?= /*I18N: Settings - section title */I18N::translate('Activate Support') ?></h3>

        <div class="row">
            <!-- activate link++ --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">[1]
                        <a href="#section1"><?= I18N::translate('Activate enhanced links?') ?></a>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                            <p><?= /*I18N: Enhanced Links */ I18N::translate('This function is implemented via Javascript and only affects links in notes and HTML blocks on the client side.') ?>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- md active --><?php $prefId = LinkEnhancerModule::PREF_MD_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        [2] <a href="#section2"><?= I18N::translate('Markdown enhancements') ?></a>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                            <p><?= /*I18N: MD img - sentence 1 */ I18N::translate('Only works in notes that are formatted with Markdown.') ?>
                            </p>
                            <p style="color: gray;"><strong><?= /*I18N: MDE */ I18N::translate("Precondition: Tree preference '%s' need to be set to markdown.", /*I18N: webtrees.pot */ I18N::translate('Format text and notes')) ?></strong>
                            <table style="color: gray;">
                              <thead><tr>
                                <th style="background-color: lightgreen; min-width:150px; text-align: center;">markdown <small>(<?= $trees_w_md_cnt ?>)</small></th>
                                <th style="background-color: rgba(236, 74, 34, 0.52); min-width:150px; text-align: center;">text <small>(<?= $trees_w_text_cnt ?>)</small></th>
                              </tr></thead>
                              <tbody><tr>
                                <td><?= $trees_w_md ?></td>
                                <td><?= $trees_w_text ?></td>
                            </tr></tbody>
                            </table>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>
           
            <!-- show wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        [3] <a href="#section3"><?= I18N::translate('Show Help Link') ?></a>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                            <p>
                                <?= /*I18N: */ I18N::translate("Context sensitive help links to the german webtrees manual can be activated in the small menu at the top of the page and for subcontext topics on the page.") ?>
                            </p>
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- home link --><?php $prefId = LinkEnhancerModule::PREF_HOME_LINK_TYPE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        [4] <a href="#section4"><?= I18N::translate('Site title as home link') ?></a>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: home link */ I18N::translate('home page of the current tree'),
                                /*I18N: home link */ I18N::translate('my page of the registered user')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>
        </div>

        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= /*I18N: webtrees.pot */ I18N::translate('save') ?>
        </button>

        <hr class="div" />
        <h3><?= /*I18N: Settings - section title */ I18N::translate('More options') ?></h3>

        <div class="row">
            <!-- debug info in js console --><?php $prefId = LinkEnhancerModule::PREF_JS_DEBUG_CONSOLE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Output of debug information on the JS console') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>

        <h4 class="subdiv">[1] <a name="section1" href="#top"><?= /*I18N: Settings - section title */I18N::translate('Enhanced Link Support') ?></a></h4>
<section id="options1">
        <div class="row">
            <!-- links++ open in new tab --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_OPEN_IN_NEW_TAB; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= /*I18N: see also fancy-research-links */ I18N::translate('Open links in a new tab') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>
            </fieldset>

            <!-- links++ javascript --><?php $prefId = LinkEnhancerModule::PREF_LINKSPP_JS; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('JavaScript for additional link targets') . ' (' . /*I18N: webtrees.pot */I18N::translate('optional') . ')' ?>
            </label>
            <div class="col-sm-9 wt-page-options-value mt-1">
                <textarea id="<?= $prefId ?>" name="<?= $prefId ?>" class="form-control font-monospace" dir="ltr" rows="5"><?= e($prefs[$prefId]) ?></textarea>
                <div class="form-text">
                    <p><?= /*I18N: Enhanced Links js */ I18N::translate('The JavaScript object overwrites and supplements the predefined settings, which are taken from the following code excerpt and can also serve as a reference point for adjustments.') ?></p>
                    <textarea class="form-control font-monospace" dir="ltr" rows="5" disabled readonly wrap="off" style="font-size:0.9em; color: gray;"><?= e($jscode_linkpp) ?></textarea>
                    <p><?= /*I18N: Enhanced Links js */ I18N::translate('Any CSS rules required are best added via the “CSS and JS” module.') ?>
                       <?= /*I18N: Enhanced Links js */ I18N::translate('Only the definition of the icon as a background image is actually needed - referencing as data: URL.') ?> <?= I18N::translate('See also') ?>: <a href="https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/data">mdn web docs - data: URLs</a>
                       <br />
                       <code>.icon-whatever { background-image: url(...) }</code>
                    </p>
                </div>
            </div>

        </div>
</section>

        <h4 class="subdiv">[2] <a name="section2" href="#top"><?= /*I18N: Settings - section title */I18N::translate('Markdown enhancements') ?></a></h4>
<section id="options2">
        <div class="row">
            <!-- md img active --><?php $prefId = LinkEnhancerModule::PREF_MD_IMG_ACTIVE; ?>
            <fieldset class="form-group mb-1">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Activate markdown image tweak?') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>

<section id="options2_1">
                <div class="row">
                    <div class="col-sm-3 col-form-label wt-page-options-label">
                        <?= I18N::translate('CSS class name(s)') ?>
                    </div>

                </div>                
                <div class="row">
                    <!-- md img stdclass --><?php $prefId = LinkEnhancerModule::PREF_MD_IMG_STDCLASS; ?>
                    <label class="col-sm-3 col-form-label wt-page-options-label sub" for="<?= $prefId ?>">
                        <?= I18N::translate('Markdown image container') ?>
                    </label>
                    <div class="col-sm-3 wt-page-options-value mt-2">
                        <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text" value="<?= e($prefs[$prefId]) ?>">
                    </div>
                    <div class="col-sm-6 mt-2 form-text">
                        <?= I18N::translate('Example') ?>:&nbsp;&nbsp; <code>md-img</code>
                    </div>

                    <!-- md img title stdclass --><?php $prefId = LinkEnhancerModule::PREF_MD_IMG_TITLE_STDCLASS; ?>
                    <label class="col-sm-3 col-form-label wt-page-options-label sub" for="<?= $prefId ?>">
                        <?= I18N::translate('Markdown image title container') ?>
                    </label>
                    <div class="col-sm-3 wt-page-options-value mt-2">
                        <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                            value="<?= e($prefs[$prefId]) ?>">
                    </div>
                    <div class="col-sm-6 mt-2 form-text">
                        <?= I18N::translate('Example') ?>:&nbsp;&nbsp; <code>md-img-title</code>
                    </div>
                </div>
</section>
            </fieldset>

            <hr class="subdiv" />

            <!-- mde active --><?php $prefId = LinkEnhancerModule::PREF_MDE_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Markdown editor for note textareas') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>

            <hr class="subdiv" />

            <!-- table cell height control --><?php $prefId = LinkEnhancerModule::PREF_MD_TD_H_CTRL_TYPE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                            <?= I18N::translate('Table cell height control') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: */ I18N::translate('available') . ' (' . I18N::translate('disabled') . ')',
                                /*I18N: */ I18N::translate('available') . ' (' . I18N::translate('enabled') . ')',
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                        <div class="form-text">
                            <?= I18N::translate('Toggle checkbox in order to set max-height and make longer content scrollable') ?>
                        </div>
                    </div>
                </div>
            </fieldset>

            <hr class="subdiv" />

            <!-- md extensions active --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_ACTIVE; ?>
            <fieldset class="form-group mb-4">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Markdown extensions') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="alert-warning mt-2 mb-2">
                            <p class="alert-title">
                                <svg class="octicon octicon-alert me-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M6.457 1.047c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0 1 14.082 15H1.918a1.75 1.75 0 0 1-1.543-2.575Zm1.763.707a.25.25 0 0 0-.44 0L1.698 13.132a.25.25 0 0 0 .22.368h12.164a.25.25 0 0 0 .22-.368Zm.53 3.996v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"></path></svg>
                                <?= I18N::translate('Warning'); ?>
                            </p>
                            <p class="form-text">
                            <?= I18N::translate('Please keep in mind when using this extensions, you are deviating from the smallest common markdown dialect set.'); ?>
                            <?= I18N::translate('If the library used to render markdown in HTML needs to be changed for any reason, there is a possibility that not all of the extended markup used here will be supported.'); ?>
                            </p>
                        </div>
                        <div class="form-text">
                            <?= I18N::translate('See also') ?>: 
                            <a href="https://github.com/bschwede/linkenhancer/issues/32#issuecomment-3761130124">#32</a> | 
                            <a href="https://commonmark.thephpleague.com/2.x/extensions/overview/">https://commonmark.thephpleague.com/2.x/extensions/overview/</a>
                        </div>
                    </div>
                </div>
            </fieldset>
<section id="options2_2">
            <!-- md extension - striketrough --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_STRIKE_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Strikethrough') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>

            <!-- md extension - definition list --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_DL_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Description list') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>

            <?php if (version_compare(Webtrees::VERSION, '2.2.5', '>=')): ?>
            <!-- md extension - highlight >= wt2.2.5 --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_MARK_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Highlight') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>
                    </div>
                </div>
            </fieldset>
            <?php endif; ?>

            <!-- md extension - footnotes --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_FN_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Footnotes') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>

<section id="options2_2_fn">
                        <!-- md extension - footnotes add hr --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_FN_ADD_HR; ?>
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start">
                                <legend class="col-form-label wt-page-options-label">
                                    <?= I18N::translate('Add hr-tag at the beginning of the footnote container') ?>
                                </legend>
                            </div>
                            <div class="col-2 d-flex  justify-content-start mt-2">
                                <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                            </div>
                            <div class="col-4 d-flex align-items-start justify-content-start form-text">
                            </div>
                        </div>

                        <!-- md extension - footnotes backref --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_FN_BACKREF_CHAR; ?>
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"> <?= I18N::translate('Backreference symbol') ?></label>
                            </div>
                            <div class="col-1 d-flex  justify-content-start">
                                <input class="form-control text-center" type="text" id="<?= e($prefId) ?>" name="<?= e($prefId) ?>"
                                    size="3" maxlength="3" value="<?= e($prefs[$prefId]) ?>">                                
                            </div>
                            <div class="col-5 d-flex align-items-start justify-content-start form-text">
                                <?= I18N::translate('Example') ?>:&nbsp;&nbsp; <code>↩</code>
                            </div>
                        </div>
</section>
                    </div>

                </div>

            </fieldset>

            <!-- md extension - table of contents --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_ACTIVE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Table of contents') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>

<section id="options2_2_toc">                       
                        <!-- md extension - toc normalize --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_NORMALIZE; ?>
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"> <?= I18N::translate('Normalize') ?></label>
                            </div>
                            <div class="col-9 d-flex  justify-content-start">
                                <?= view('components/select', [
                                    'name' => $prefId, 
                                    'selected' => $prefs[$prefId], 
                                    'options' => prefixKeysToValues(CustomMarkdownFactory::getExtensionSettingOptions(ExtensionSettingOption::TOC_NORMALIZE))
                                ]) ?>
                            </div>
                        </div>
                        
                        <!-- md extension - toc style --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_STYLE; ?>
<section id="md-toc-style">
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"> <?= I18N::translate('Style') ?></label>
                            </div>
                            <div class="col-9 d-flex  justify-content-start">
                                <?= view('components/select', [
                                    'name' => $prefId, 
                                    'selected' => $prefs[$prefId], 
                                    'options' => prefixKeysToValues(CustomMarkdownFactory::getExtensionSettingOptions(ExtensionSettingOption::TOC_STYLE))
                                ]) ?>
                            </div>
                        </div>
</section>

                        <!-- md extension - toc position --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_POS; ?>
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"> <?= I18N::translate('Position') ?></label>
                            </div>
                            <div class="col-9 d-flex  justify-content-start">
                                <?= view('components/select', [
                                    'name' => $prefId, 
                                    'selected' => $prefs[$prefId], 
                                    'options' => prefixKeysToValues(CustomMarkdownFactory::getExtensionSettingOptions(ExtensionSettingOption::TOC_POSITION))
                                ]) ?>
                            </div>
                        </div>

                        <!-- md extension - toc placeholder --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_PLACEHOLDER; ?>
<section id="pos-is-placeholder">
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1 sub">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"> <?= I18N::translate('Placeholder') ?></label>
                            </div>
                            <div class="col-3 d-flex  justify-content-start">
                                <input class="form-control" type="text" id="<?= e($prefId) ?>" name="<?= e($prefId) ?>" value="<?= e($prefs[$prefId]) ?>">
                            </div>
                            <div class="col-5 d-flex align-items-start justify-content-start form-text">
                                <?= I18N::translate('Example') ?>:&nbsp;&nbsp; <code>[TOC]</code>
                            </div>
                        </div>
</section>

                        <!-- md extension - toc css class name --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_CSSCLASS; ?>
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"><?= I18N::translate('CSS class name(s)') ?></label>
                            </div>
                            <div class="col-3 d-flex  justify-content-start">
                                <input class="form-control" type="text" id="<?= e($prefId) ?>" name="<?= e($prefId) ?>" value="<?= e($prefs[$prefId]) ?>">
                            </div>
                            <div class="col-5 d-flex align-items-start justify-content-start form-text">
                                <?= I18N::translate('Example') ?>:&nbsp;&nbsp; <code>float-end</code>
                            </div>
                        </div>

                        <!-- md extension - toc permalink --><?php $prefId = LinkEnhancerModule::PREF_MD_EXT_TOC_PERMALINK_CHAR; ?>
                        <div class="row mt-2 mb-1">
                            <div class="col-3 d-flex align-items-center justify-content-start mt-1">
                                <label for="<?= e($prefId) ?>" class="me-1 mb-0"> <?= I18N::translate('Permalink symbol') ?></label>
                            </div>
                            <div class="col-1 d-flex  justify-content-start">
                                <input class="form-control text-center" type="text" id="<?= e($prefId) ?>" name="<?= e($prefId) ?>"
                                    size="3" maxlength="3" value="<?= e($prefs[$prefId]) ?>">                                
                            </div>
                            <div class="col-2 d-flex align-items-start justify-content-start form-text"></div>
                            <div class="col-5 d-flex align-items-start justify-content-start form-text">
                                <?= I18N::translate('Example') ?>:&nbsp;&nbsp; <code>¶ #</code>
                            </div>
                        </div>                        

</section>
                    </div>
                </div>
            </fieldset>
</section>
        </div>
</section>

        <h4 class="subdiv">[3] <a name="section3" href="#top"><?= /*I18N: Settings - section title */ I18N::translate('Webtrees manual') ?></a></h4>
<section id="options3">
        <div class="row">
            <!-- prepend faicon to wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_FAICON; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <i class="fa-solid fa-circle-question"></i> <?= I18N::translate('Precede the help link with an icon') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>
            </fieldset>
        
            <!-- support subcontext wthb-links --><?php $prefId = LinkEnhancerModule::PREF_WTHB_SUBCONTEXT; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate('Help link for subcontext topics') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>
            </fieldset>

            <!-- full-text search and toc --><?php $prefId = LinkEnhancerModule::PREF_WTHB_TOCNSEARCH; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= I18N::translate("Full-text search") . ' / ' . I18N::translate('Table of contents') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>
            </fieldset>

            <!-- translate wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_TRANSLATE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label">
                        <?= /*I18N: wthb link setting option */ I18N::translate('Open webtrees manual URL with Google Translate?') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= view('components/radios-inline', [
                            'id' => $prefId,
                            'name' => $prefId,
                            'options' => [
                                /*I18N: webtrees.pot */ I18N::translate('no'),
                                /*I18N: wthb translate */ I18N::translate('user defined'),
                                /*I18N: webtrees.pot */ I18N::translate('yes')
                            ],
                            'selected' => (int) $prefs[$prefId]
                        ]) ?>
                    </div>
                </div>
            </fieldset>

            
            <div class="row">
                <div class="col-form-label col-sm-3 wt-page-options-label">
                    <?= I18N::translate('Help link in the admin backend') ?>
                </div>
                <div class="col-sm-9 wt-page-options-value">
                    <div class="form-text">
                        <p><?= I18N::translate('Vesta modules override the admin layout view and provide a way to insert code through custom modules.') ?><br>
                        <?= I18N::translate('As they are frequently used, this module first attempts this approach.') ?>
                        </p>
                        <p>vesta_common <?= ($vesta_common_enabled ? "✅" : "❌") ?></p>
                    </div>                    
                </div>
            </div>


            <!-- fallback admin view patch --><?php $prefId = LinkEnhancerModule::PREF_WTHB_ADMINVIEWPATCH; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Fallback patch for admin layout view') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                        <div class="form-text">
                        </div>                    
                    </div>
                </div>
            </fieldset>

            <hr class="subdiv" />
            
            <!-- genwiki std link --><?php $prefId = LinkEnhancerModule::PREF_GENWIKI_LINK; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('Link to GenWiki') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                    value="<?= e($prefs[$prefId]) ?>">
                <div class="form-text">
                    <p><?= /*I18N: WTHB Link */ I18N::translate('This is the base link that is combined with the relative context links from the database table.') ?>
                    </p>
                </div>
            </div>
        
            <!-- wthb std link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_STD_LINK; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('Standard Link to webtrees manual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" id="<?= $prefId ?>" name="<?= $prefId ?>" type="text"
                    value="<?= e($prefs[$prefId]) ?>">
                <div class="form-text">
                    <p><?= /*I18N: WTHB Link */ I18N::translate('This fallback link is used, when no specific context link was defined.') ?>
                    </p>
                </div>
            </div>

            <hr class="subdiv" />

            <!-- wthb mapping data table -->
            <div class="col-sm-3 col-form-label wt-page-options-label">
                <?= I18N::translate('Data table') ?>
            </div>
            <div class="col-sm-9 wt-page-options-value">
                <div class="form-text">
                    <p><?= /*I18N: WTHB Link table */ I18N::translate('The context is established by assigning the routes used in webtrees to the corresponding sections in the manual.') ?>
                        <br>
                        <?= /*I18N: WTHB Link table */ I18N::translate('The data is stored in the database table') ?>:
                        <code><?= DB::prefix(LinkEnhancerModule::HELP_TABLE) ?></code>
                        <em>(<strong><?= /*I18N: WTHB Link table rows */ I18N::translate('Data rows') ?>:</strong>
                            <?= /*I18N: WTHB Link table rows assigned/total */ I18N::translate('%s of %s assigned', $tablerows['assigned'] ?? 0, $tablerows['total'] ?? 0) ?>)</em>
                    </p>
                </div>                    
                <div class="row mt-1">
                    <div class="col-5 d-flex align-items-center justify-content-start">
                        <a class="btn btn-secondary"
                            href="<?= e($links['routeimport']) ?>"><?= I18N::translate('Import registered routes') ?></a>
                    </div>
                    <div class="col-2 d-flex align-items-center justify-content-start" title="<?= e(I18N::translate('truncate table before import routes or csv file')) ?>">
                        <input type="checkbox" class="form-check-input me-1" name="table-truncate" id="table-truncate" value="1">
                        <label class="form-check-label ms-1 mb-0" for="table-truncate"> <?= I18N::translate('Table truncate') ?></label>
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-end">
                        <a class="btn btn-secondary"
                            href="<?= e($links['resetroutes']) ?>"><?= I18N::translate('Reset routes to delivery status') ?></a>
                    </div>

                </div>
                <div class="row mt-3 mb-1">
                    <div class="col-5 d-flex align-items-center justify-content-start">
                        <button type="submit" class="btn btn-secondary" formaction="<?= e($links['csvimport']) ?>">
                            <?= I18N::translate('CSV-Import') ?>
                        </button>
                    </div>
                    <div class="col-2 d-flex align-items-center justify-content-center">
                        <label for="csv-separator" class="me-1 mb-0"> <?= I18N::translate('Separator') ?></label>
                        <input class="form-control form-control-sm text-center" type="text" id="csv-separator" name="csv-separator" size="3" maxlength="3" value=";" required>
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-end">
                        <button type="submit" class="btn btn-secondary" formaction="<?= e($links['csvexport']) ?>">
                            <?= I18N::translate('CSV-Export') ?>
                        </button>

                    </div>
                </div>
                <div class="row mt-1 mb-1">
                    <label for="csv-file" class="col-sm-3 mt-2">
                        <?= I18N::translate('CSV import file') ?>
                    </label>
                
                    <div class="col-sm-9">
                        <input id="csv-file" type="file" name="csv-file" class="form-control">
                    </div>
                </div>
                <div class="row mt-1 mb-3">
                    <label for="encoding" class="col-sm-3 mt-2">
                        <?= /*I18N: webtrees.pot */ I18N::translate('Character encoding') ?>
                    </label>
                    
                    <div class="col-sm-9">
                        <?= view('components/select', ['name' => 'encoding', 'selected' => '', 'options' => ['' => /*I18N: webtrees.pot */I18N::translate('automatic')] + Registry::encodingFactory()->list()]) ?>
                    </div>
                </div>
            </div>
        
            <!-- auto update to wthb-link --><?php $prefId = LinkEnhancerModule::PREF_WTHB_UPDATE; ?>
            <fieldset class="form-group mb-3">
                <div class="row">
                    <legend class="col-form-label col-sm-3 wt-page-options-label sub">
                        <?= I18N::translate('Automatically refresh data table when module is updated') ?>
                    </legend>
                    <div class="col-sm-9 wt-page-options-value mt-2">
                        <?= insertNoYesInlineRadiobuttons($prefId, $prefs[$prefId]) ?>
                    </div>
                </div>
            </fieldset>
        </div>
</section>

        <h4 class="subdiv">[4] <a name="section4" href="#top"><?= /*I18N: Settings - section title */ I18N::translate('Home link') ?></a></h4>
<section id="options4">
        <div class="row">
            <!-- home link --><?php $prefId = LinkEnhancerModule::PREF_HOME_LINK_JSON; ?>
            <label class="col-sm-3 col-form-label wt-page-options-label" for="<?= $prefId ?>">
                <?= I18N::translate('JSON for home link styling') . ' (' . /*I18N: webtrees.pot */ I18N::translate('optional') . ')' ?>
            </label>
            <div class="col-sm-9 wt-page-options-value mt-3">
                <textarea id="<?= $prefId ?>" name="<?= $prefId ?>" class="form-control font-monospace" dir="ltr"
                    rows="5"><?= e($prefs[$prefId]) ?></textarea>
                <div class="form-text">
                    <p><?= /*I18N: Home link js */ I18N::translate('JSON object that can be used to dynamically apply CSS styles for the home link that match the current theme.') ?>
                    <br>
                    <?= /*I18N: Home link js */ I18N::translate('Standard CSS class name') ?>: <code><?= LinkEnhancerModule::STDCLASS_HOME_LINK ?></code>
                    </p>
                    <p><?= /*I18N: Home link js */ I18N::translate('Example') ?>: <code><?= LinkEnhancerModule::EXAMPLE_HOME_LINK_JSON ?></code></p>
                </div>
            </div>
        </div>
</section>

        <p>&nbsp;</p>

        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= /*I18N: webtrees.pot */I18N::translate('save') ?>
        </button>
    </form>
</div>

<?php View::push('javascript') ?>
<script>
    function checkForm(message) {
        const showError = (elem, msg) => {
            let errId = 'error-' + elem.attr('id');
            let errElem = $(`#${errId}`);
            console.log(errElem);
            if (errElem.length == 1) {
                $(errElem).text(msg);
            } else {
                $(elem).after(`<div id="${errId}" class="error">${msg}</div>`);
            }
        }
        
        let firstErrElem = null;

        let linkspp = $('#<?= LinkEnhancerModule::PREF_LINKSPP_JS; ?>');
        let jsString = linkspp.val().trim();
        if (jsString) {
            try {
                eval(`() => { let a = ${jsString}}`);
            } catch (e) { 
                showError(linkspp, '<?= e(I18N::translate('Javascript is invalid')) ?>: ' + e.message);
                firstErrElem ??= linkspp;
            }
        }

        let homelink = $('#<?= LinkEnhancerModule::PREF_HOME_LINK_JSON; ?>');
        let jsonString = homelink.val().trim();
        if (jsonString) {
            try {
                const obj = JSON.parse(jsonString); // Syntax-Validierung
            } catch (e) {
                showError(homelink, '<?= e(I18N::translate('JSON is invalid')) ?>');
                firstErrElem ??= homelink;
            }
        }

        if (firstErrElem) {
            $(firstErrElem).get(0).scrollIntoView({behavior: 'smooth'});
            return false;
        }
        return true;
    }

    document.querySelectorAll('a[href^="#"]').forEach(link => {
        link.addEventListener('click', event => {
            event.preventDefault();
            let id = link.hash.substring(1);
            let elem = (id === 'top' ? document.documentElement : document.querySelector(`[id="${id}"], [name="${id}"]`));
            if (elem) {
                elem.scrollIntoView({ behavior: 'smooth' });
            }
            return false;
        });
    });

    function toggleSectionByRadio(secId, radioGroupname, cname) {
        console.log(secId, radioGroupname, cname)
        let section = $(`#${secId}`);
        if ($(`#${radioGroupname}-0:checked`).length == 1) { // radio "no" is selected - disable
            $(section).addClass(cname);
        } else {
            $(section).removeClass(cname);
        }
    }

    function toggleSectionBySelectSingle(secId, selectName, cname, checkvalues, disableifincluded = true) {
        let section = $(`#${secId}`);
        let selectvalue = $(`select[name="${selectName}"]`).val();
        checkvalues = Array.isArray(checkvalues) ? checkvalues : [ checkvalues ];
        invalues = checkvalues.includes(selectvalue);
        if (disableifincluded && invalues || !disableifincluded && !invalues) {
            $(section).addClass(cname);
        } else {
            $(section).removeClass(cname);
        }
    }

    $(()=> {
        [['<?= LinkEnhancerModule::PREF_LINKSPP_ACTIVE; ?>', 1],
        ['<?= LinkEnhancerModule::PREF_MD_ACTIVE; ?>', 2],
        ['<?= LinkEnhancerModule::PREF_MD_IMG_ACTIVE; ?>', '2_1'],
        ['<?= LinkEnhancerModule::PREF_MD_EXT_ACTIVE; ?>', '2_2'],
        ['<?= LinkEnhancerModule::PREF_MD_EXT_FN_ACTIVE; ?>', '2_2_fn'],
        ['<?= LinkEnhancerModule::PREF_MD_EXT_TOC_ACTIVE; ?>', '2_2_toc'],
        ['<?= LinkEnhancerModule::PREF_WTHB_ACTIVE; ?>', 3],
        ['<?= LinkEnhancerModule::PREF_HOME_LINK_TYPE; ?>', 4]].forEach( (sec) => {
            [secName, secIdx ] = sec;
            ((name, idx) => {
                $(`input[type=radio][name='${name}']`).on("change", () => {toggleSectionByRadio('options' + idx, name, 'disabled-w-text')});
            })(secName, secIdx);
            toggleSectionByRadio('options' + secIdx, secName, 'disabled-w-text');
        });

        [['<?= LinkEnhancerModule::PREF_MD_EXT_TOC_POS; ?>', 'pos-is-placeholder', [ 'placeholder' ], false ],
        ['<?= LinkEnhancerModule::PREF_MD_EXT_TOC_NORMALIZE; ?>', 'md-toc-style', [ 'flat-inline' ], true ]
        ].forEach( (elem) => {
            [selname, secId, cvalues, dii ] = elem;
            ((selname, secId, cvalues, dii=true) => {
                $(`select[name='${selname}']`).on("change", () => {toggleSectionBySelectSingle(secId, selname, 'disabled', cvalues, dii)});
            })(selname, secId, cvalues, dii);
            toggleSectionBySelectSingle(secId, selname, 'disabled', cvalues, dii);            
        });
    });
</script>
<?php View::endpush() ?>

<?php View::push('styles') ?>
<style>
.error {
    color: #d00;
    font-weight: bold;
}
hr.div {
    border-top: 2px solid black;
}
hr.subdiv {
  width: 96%;
  margin: 0.5em 2% 0.5em 2% !important;
  border: 1px silver solid !important;
}
h4.subdiv {
  border-bottom:1px solid black;
  margin-top: 1.2em;
}
.sub {
  padding-left: 3.0em !important;
}
.linkenhancer {
  padding-bottom:60vh;
}
.treelist {
  max-height: 6.0em;
  overflow: auto;
}
.alert-warning {
  border-left: .25em solid #d29922;
  padding: 0.5rem 1rem;
}
.alert-title {
  display: flex;
  font-weight: 500;
  align-items: center;
  line-height: 1;
  color: #d29922;    
}
.octicon {
  display: inline-block;
  overflow: visible !important;
  vertical-align: text-bottom;
  fill: currentColor;
}

.disabled {
  display: none;
}
.disabled-w-text {
  max-height: 2.0em;
  overflow: clip;
}
.disabled-w-text::before {
  content: "<?= I18N::translate('Enable for more options') ?>...";
  color: gray;
}
</style>
<?php View::endpush() ?>