<?php
// https://github.com/fisharebest/webtrees/blob/main/resources/views/layouts/administration.phtml
declare(strict_types=1);

use Fisharebest\Webtrees\FlashMessages;
use Schwendinger\Webtrees\Helpers\ClassName;
use Schwendinger\Webtrees\Helpers\Functions;
use Fisharebest\Webtrees\I18N;
use Schwendinger\Webtrees\Helpers\MoreI18N;
use Fisharebest\Webtrees\Module\CustomCssJsModule;
use Fisharebest\Webtrees\Module\ModuleCustomInterface;
use Fisharebest\Webtrees\Module\ModuleGlobalInterface;
use Fisharebest\Webtrees\Registry;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\View;

/**
 * @var string $title
 * @var string $content
 */

if (Functions::wtIsAtLeast2_3()) {
    $html_dir = I18N::textDirection()->value;
    $html_lang = I18N::languageTag();
    $homepage_a_display = MoreI18N::xlate('Exit control panel');
} else {
    $html_dir = I18N::locale()->direction();
    $html_lang = I18N::locale()->languageTag();
    $homepage_a_display = MoreI18N::xlate('My page');
}

?>

<!DOCTYPE html>
<html dir="<?= $html_dir ?>" lang="<?= $html_lang ?>">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf" content="<?= e(csrf_token()) ?>">

        <title><?= strip_tags($title) ?></title>

        <link rel="icon" href="<?= e(asset('favicon.ico')) ?>" type="image/x-icon">

        <link rel="stylesheet" href="<?= e(asset('css/vendor.min.css')) ?>">
        <link rel="stylesheet" href="<?= e(asset('css/administration.min.css')) ?>">

        <?= View::stack('styles') ?>

        <?= Registry::container()->get(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
            return $module instanceof ModuleCustomInterface && !preg_match('/LinkEnhancerModule/i', get_class($module)) || $module instanceof CustomCssJsModule ? '' : $module->headContent();
        })->implode('') /* =-Fix-P002-= */ ?>
    </head>
    <body class="container-lg wt-global wt-control-panel">
        <header>
            <div class="wt-accessibility-links position-fixed">
                <a class="visually-hidden visually-hidden-focusable btn btn-info btn-sm" href="#content">
                    <?= /* I18N: Skip over the headers and menus, to the main content of the page */
                        MoreI18N::xlate('Skip to content') ?>
                </a>
            </div>

            <ul class="nav small d-flex justify-content-end">
                <li class="nav-item menu-mypage">
                    <a class="nav-link active" href="<?= e(route(ClassName::get(ClassName::HOME_PAGE))) ?>"><?= $homepage_a_display ?></a>
                </li>
                <li class="nav-item dropdown menu-language">
                    <a class="nav-link dropdown-toggle" id="admin-language-menu" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        <?= MoreI18N::xlate('Language') ?>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="admin-language-menu">
                <?php if (Functions::wtIsAtLeast2_3()): ?>
                    <?php foreach (I18N::activeLanguages() as $language_tag => $endonym): ?>
                        <a class="dropdown-item menu-language-<?= $language_tag ?> <?= I18N::languageTag() === $language_tag ? ' active' : '' ?>" href="#" data-wt-post-url="<?= e(route(ClassName::get(ClassName::SELECT_LANGUAGE), ['language' => $language_tag])) ?>"><?= $endonym ?></a>
                    <?php endforeach ?>
                <?php else: ?>
                    <?php foreach (I18N::activeLocales() as $locale): ?>
                        <a class="dropdown-item menu-language-<?= $locale->languageTag() ?> <?= I18N::languageTag() === $locale->languageTag() ? ' active' : '' ?>" href="#" data-wt-post-url="<?= e(route(ClassName::get(ClassName::SELECT_LANGUAGE), ['language' => $locale->languageTag()])) ?>"><?= $locale->endonym() ?></a>
                    <?php endforeach ?>
                <?php endif; ?>
                    </div>
                </li>
                <li class="nav-item menu-logout">
                    <a class="nav-link" href="#" data-wt-post-url="<?= e(route(ClassName::get(ClassName::LOGOUT_PAGE))) ?>" data-wt-reload-url="<?= e(route(ClassName::get(ClassName::HOME_PAGE))) ?>"><?= MoreI18N::xlate('Sign out') ?></a>
                </li>
            </ul>
        </header>

        <main id="content">
            <?php foreach (FlashMessages::getMessages() as $message): ?>
                    <div class="alert alert-<?= $message->status ?> alert-dismissible" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="<?= MoreI18N::xlate('close') ?>">
                        </button>
                        <?= $message->text ?>
                    </div>
            <?php endforeach ?>

            <?= $content ?>
        </main>


        <script src="<?= e(asset('js/vendor.min.js')) ?>"></script>
        <?php if (Functions::wtIsAtLeast2_3()): ?>
        <script src="<?= e(asset('js/i18n/' . I18N::languageTag() . '.js')) ?>"></script>
        <?php endif; ?>
        <script src="<?= e(asset('js/webtrees.min.js')) ?>"></script>
        <?php if (Functions::wtIsAtLeast2_3()): ?>
        <script src="<?= e(asset('js/administration.min.js')) ?>"></script>
        <?php endif; ?>

        <?= View::stack('javascript') ?>

        <?= Registry::container()->get(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
            return $module instanceof ModuleCustomInterface && !preg_match('/LinkEnhancerModule/i', get_class($module)) || $module instanceof CustomCssJsModule ? '' : $module->bodyContent();
        })->implode('') /* =-Fix-P002-= */ ?>
    </body>
</html>
